author: Yukang
description: All about coding and software
keyword: Programming, Programming Languages, Algorithms, Tools
favicon:

excerpt_link: Continue Read ...

menu:
 Home: /
 Algo&DS: /algorithms-and-data-structures/
 System: /system/
 Language: /Languages/
 Archives: /archives/
 About: /about/

# highlight
highlight:
  agate
  #monokai-sublime
  #dracula
  #solarized-dark

github_username: 
zhihu_username: 
douban_username: 


# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment or uyan

comment: gitment

# gitment config
gitment_owner: 
gitment_repo: 
gitment_oauth_id: 
gitment_oauth_secret: 

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: ba1315646a61cc7bd6f574a6b5221640

about:
  banner: /css/images/head_background.jpg
  avatar: https://avatars1.githubusercontent.com/u/230646?v=4&s=460
  description: "Dont't Panic"
  twitter_username: 
  github_username: 
  zhihu_username: 
  douban_username: 

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
